local need  = require "need"
local core = require("lua-light-wings")
core.globalize(core)
local html_utils = need "html_utils"

local content_block = [[
This text is part of a HTML chunk, which was generated by a Lua script and
dynamically loaded with HTMX in the dom.
]]

local html = html_utils.format(content_block, "b")
ngx.say(html)