local html_utils = require("modules.html_utils")

local content_block = [[
This text is part of a HTML chunk, which was generated by a Lua script and
dynamicly loaded with HTMX in the dom.
]]

local html = html_utils.format(content_block, "b")
ngx.say(html)